import { Elysia, t } from "elysia";
import {
  listStudentsController,
  getStudentByIdController,
  createStudentController,
  updateStudentController,
  deleteStudentController,
  listStudentEnrollmentsController,
  listStudentSubjectsController,
  listStudentScoresController,
  listStudentSubjectScoresController,
} from "../../controllers/admin/student.controller";

export const studentRoutes = new Elysia({ prefix: "/students" })
  .get("/", listStudentsController, {
    query: t.Object({
      studentLevelId: t.Optional(t.String()),
      programEducationId: t.Optional(t.String()),
      classroomId: t.Optional(t.String()),
      search: t.Optional(t.String()),
      page: t.Optional(t.String()),
      pageSize: t.Optional(t.String()),
    }),
    tags: ["Student (AdminRoutes)"],
    summary: "รายชื่อนักเรียนทั้งหมด",
  })
  .get("/:id", getStudentByIdController, {
    params: t.Object({ id: t.String() }),
    tags: ["Student (AdminRoutes)"],
    summary: "ข้อมูลนักเรียนรายคน",
  })
  .post("/create", createStudentController, {
    body: t.Object({
      studentCode: t.String(),
      studentCodeOpec: t.Optional(t.String()),
      idCardNo: t.Optional(t.String()),
      prefix: t.Optional(t.String()),
      firstName: t.String(),
      lastName: t.String(),
      firstNameEn: t.Optional(t.String()),
      lastNameEn: t.Optional(t.String()),
      nickname: t.Optional(t.String()),
      nicknameEn: t.Optional(t.String()),
      nationality: t.Optional(t.String()),
      ethnicity: t.Optional(t.String()),
      religion: t.Optional(t.String()),
      birthDate: t.Optional(t.String()),
      gender: t.Optional(t.String()),
      addresshomeNo: t.Optional(t.String()),
      addressRoad: t.Optional(t.String()),
      addressMoo: t.Optional(t.String()),
      addressTambon: t.Optional(t.String()),
      addressAmphoe: t.Optional(t.String()),
      addressProvince: t.Optional(t.String()),
      addressPostcode: t.Optional(t.String()),
      previousSchool: t.Optional(t.String()),
      previousSchoolAddressAmphore: t.Optional(t.String()),
      previousSchoolAddressProvince: t.Optional(t.String()),
      previousSchoolReasonMove: t.Optional(t.String()),
      homePhone: t.Optional(t.String()),
      mobilePhone: t.Optional(t.String()),
      fammilyRelationship: t.Optional(t.String()),
      guardianPrefix: t.Optional(t.String()),
      guardianFirstName: t.Optional(t.String()),
      guardianLastName: t.Optional(t.String()),
      guardianNationality: t.Optional(t.String()),
      guardianEthnicity: t.Optional(t.String()),
      guardianReligion: t.Optional(t.String()),
      guardianBloodGroup: t.Optional(t.String()),
      guardianIdCardNo: t.Optional(t.String()),
      guardianWorkplace: t.Optional(t.String()),
      guardianIncomeRange: t.Optional(t.String()),
      guardianPhone: t.Optional(t.String()),
      guardianHomePhone: t.Optional(t.String()),
      guardianRelationship: t.Optional(t.String()),
      guardianAddressHomeNo: t.Optional(t.String()),
      guardianAddressRoad: t.Optional(t.String()),
      guardianAddressMoo: t.Optional(t.String()),
      guardianAddressTambon: t.Optional(t.String()),
      guardianAddressAmphoe: t.Optional(t.String()),
      guardianAddressProvince: t.Optional(t.String()),
      guardianAddressPostcode: t.Optional(t.String()),
      guardianIdCardFileUrl: t.Optional(t.String()),
      guardianHouseRegistrationFileUrl: t.Optional(t.String()),
      fatherPrefix: t.Optional(t.String()),
      fatherFirstName: t.Optional(t.String()),
      fatherLastName: t.Optional(t.String()),
      fatherNationality: t.Optional(t.String()),
      fatherEthnicity: t.Optional(t.String()),
      fatherReligion: t.Optional(t.String()),
      fatherBloodGroup: t.Optional(t.String()),
      fatherStatus: t.Optional(t.Boolean()),
      fatherIdCardNo: t.Optional(t.String()),
      fatherOccupation: t.Optional(t.String()),
      fatherWorkplace: t.Optional(t.String()),
      fatherIncomeRange: t.Optional(t.String()),
      fatherPhone: t.Optional(t.String()),
      fatherIdCardFileUrl: t.Optional(t.String()),
      fatherHouseRegistrationFileUrl: t.Optional(t.String()),
      motherPrefix: t.Optional(t.String()),
      motherFirstName: t.Optional(t.String()),
      motherLastName: t.Optional(t.String()),
      motherNationality: t.Optional(t.String()),
      motherEthnicity: t.Optional(t.String()),
      motherReligion: t.Optional(t.String()),
      motherBloodGroup: t.Optional(t.String()),
      motherStatus: t.Optional(t.Boolean()),
      motherIdCardNo: t.Optional(t.String()),
      motherOccupation: t.Optional(t.String()),
      motherWorkplace: t.Optional(t.String()),
      motherIncomeRange: t.Optional(t.String()),
      motherPhone: t.Optional(t.String()),
      motherIdCardFileUrl: t.Optional(t.String()),
      motherHouseRegistrationFileUrl: t.Optional(t.String()),
      houseRegistrationFileUrl: t.Optional(t.String()),
      previousSchoolFileUrl: t.Optional(t.String()),
      studentLevelId: t.Optional(t.String()),
      isActive: t.Optional(t.Boolean()),
      note: t.Optional(t.String()),
      classroomId: t.Optional(t.String()),
      programEducationId: t.Optional(t.String()),
    }),
    tags: ["Student (AdminRoutes)"],
    summary: "เพิ่มนักเรียน",
  })
  .patch("/update/:id", updateStudentController, {
    params: t.Object({ id: t.String() }),
    body: t.Object({
      studentCode: t.Optional(t.String()),
      studentCodeOpec: t.Optional(t.String()),
      idCardNo: t.Optional(t.String()),
      prefix: t.Optional(t.String()),
      firstName: t.Optional(t.String()),
      lastName: t.Optional(t.String()),
      firstNameEn: t.Optional(t.String()),
      lastNameEn: t.Optional(t.String()),
      nickname: t.Optional(t.String()),
      nicknameEn: t.Optional(t.String()),
      nationality: t.Optional(t.String()),
      ethnicity: t.Optional(t.String()),
      religion: t.Optional(t.String()),
      birthDate: t.Optional(t.String()),
      gender: t.Optional(t.String()),
      addresshomeNo: t.Optional(t.String()),
      addressRoad: t.Optional(t.String()),
      addressMoo: t.Optional(t.String()),
      addressTambon: t.Optional(t.String()),
      addressAmphoe: t.Optional(t.String()),
      addressProvince: t.Optional(t.String()),
      addressPostcode: t.Optional(t.String()),
      previousSchool: t.Optional(t.String()),
      previousSchoolAddressAmphore: t.Optional(t.String()),
      previousSchoolAddressProvince: t.Optional(t.String()),
      previousSchoolReasonMove: t.Optional(t.String()),
      homePhone: t.Optional(t.String()),
      mobilePhone: t.Optional(t.String()),
      fammilyRelationship: t.Optional(t.String()),
      guardianPrefix: t.Optional(t.String()),
      guardianFirstName: t.Optional(t.String()),
      guardianLastName: t.Optional(t.String()),
      guardianNationality: t.Optional(t.String()),
      guardianEthnicity: t.Optional(t.String()),
      guardianReligion: t.Optional(t.String()),
      guardianBloodGroup: t.Optional(t.String()),
      guardianIdCardNo: t.Optional(t.String()),
      guardianWorkplace: t.Optional(t.String()),
      guardianIncomeRange: t.Optional(t.String()),
      guardianPhone: t.Optional(t.String()),
      guardianHomePhone: t.Optional(t.String()),
      guardianRelationship: t.Optional(t.String()),
      guardianAddressHomeNo: t.Optional(t.String()),
      guardianAddressRoad: t.Optional(t.String()),
      guardianAddressMoo: t.Optional(t.String()),
      guardianAddressTambon: t.Optional(t.String()),
      guardianAddressAmphoe: t.Optional(t.String()),
      guardianAddressProvince: t.Optional(t.String()),
      guardianAddressPostcode: t.Optional(t.String()),
      guardianIdCardFileUrl: t.Optional(t.String()),
      guardianHouseRegistrationFileUrl: t.Optional(t.String()),
      fatherPrefix: t.Optional(t.String()),
      fatherFirstName: t.Optional(t.String()),
      fatherLastName: t.Optional(t.String()),
      fatherNationality: t.Optional(t.String()),
      fatherEthnicity: t.Optional(t.String()),
      fatherReligion: t.Optional(t.String()),
      fatherBloodGroup: t.Optional(t.String()),
      fatherStatus: t.Optional(t.Boolean()),
      fatherIdCardNo: t.Optional(t.String()),
      fatherOccupation: t.Optional(t.String()),
      fatherWorkplace: t.Optional(t.String()),
      fatherIncomeRange: t.Optional(t.String()),
      fatherPhone: t.Optional(t.String()),
      fatherIdCardFileUrl: t.Optional(t.String()),
      fatherHouseRegistrationFileUrl: t.Optional(t.String()),
      motherPrefix: t.Optional(t.String()),
      motherFirstName: t.Optional(t.String()),
      motherLastName: t.Optional(t.String()),
      motherNationality: t.Optional(t.String()),
      motherEthnicity: t.Optional(t.String()),
      motherReligion: t.Optional(t.String()),
      motherBloodGroup: t.Optional(t.String()),
      motherStatus: t.Optional(t.Boolean()),
      motherIdCardNo: t.Optional(t.String()),
      motherOccupation: t.Optional(t.String()),
      motherWorkplace: t.Optional(t.String()),
      motherIncomeRange: t.Optional(t.String()),
      motherPhone: t.Optional(t.String()),
      motherIdCardFileUrl: t.Optional(t.String()),
      motherHouseRegistrationFileUrl: t.Optional(t.String()),
      houseRegistrationFileUrl: t.Optional(t.String()),
      previousSchoolFileUrl: t.Optional(t.String()),
      studentIdCardFileUrl: t.Optional(t.String()),
      profileStudentImageUrl: t.Optional(t.String()),
      studentLevelId: t.Optional(t.String()),
      isActive: t.Optional(t.Boolean()),
      note: t.Optional(t.String()),
      classroomId: t.Optional(t.String()),
      programEducationId: t.Optional(t.String()),
    }),
    tags: ["Student (AdminRoutes)"],
    summary: "แก้ไขข้อมูลนักเรียน",
  })
  .delete("/delete/:id", deleteStudentController, {
    params: t.Object({ id: t.String() }),
    tags: ["Student (AdminRoutes)"],
    summary: "ลบนักเรียน",
  })
  .get("/:id/enrollments", listStudentEnrollmentsController, {
    params: t.Object({ id: t.String() }),
    tags: ["Student (AdminRoutes)"],
    summary: "ดูวิชาที่นักเรียนลงทะเบียน",
  })
  .get("/:id/subjects", listStudentSubjectsController, {
    params: t.Object({ id: t.String() }),
    tags: ["Student (AdminRoutes)"],
    summary: "ดูรายชื่อวิชาที่นักเรียนลงทะเบียน",
  })
  .get("/:id/scores", listStudentScoresController, {
    params: t.Object({ id: t.String() }),
    tags: ["Student (AdminRoutes)"],
    summary: "ดูคะแนนนักเรียนทุกวิชา/ตัวชี้วัด",
  })
  .get("/:id/subjects/:subjectId/scores", listStudentSubjectScoresController, {
    params: t.Object({ id: t.String(), subjectId: t.String() }),
    tags: ["Student (AdminRoutes)"],
    summary: "ดูคะแนนนักเรียนในวิชานี้ (ทุกตัวชี้วัด)",
  });
